/** Paesi comuni per nazionalità / emissione documento (UI checkout). */

export type CountryOption = { code: string; label: string };

export const COUNTRY_OPTIONS: CountryOption[] = [
  { code: 'IT', label: 'Italia' },
  { code: 'SM', label: 'San Marino' },
  { code: 'VA', label: 'Città del Vaticano' },
  { code: 'CH', label: 'Svizzera' },
  { code: 'AT', label: 'Austria' },
  { code: 'FR', label: 'Francia' },
  { code: 'DE', label: 'Germania' },
  { code: 'ES', label: 'Spagna' },
  { code: 'PT', label: 'Portogallo' },
  { code: 'GB', label: 'Regno Unito' },
  { code: 'IE', label: 'Irlanda' },
  { code: 'NL', label: 'Paesi Bassi' },
  { code: 'BE', label: 'Belgio' },
  { code: 'LU', label: 'Lussemburgo' },
  { code: 'GR', label: 'Grecia' },
  { code: 'HR', label: 'Croazia' },
  { code: 'SI', label: 'Slovenia' },
  { code: 'PL', label: 'Polonia' },
  { code: 'CZ', label: 'Cechia' },
  { code: 'SK', label: 'Slovacchia' },
  { code: 'HU', label: 'Ungheria' },
  { code: 'RO', label: 'Romania' },
  { code: 'BG', label: 'Bulgaria' },
  { code: 'SE', label: 'Svezia' },
  { code: 'NO', label: 'Norvegia' },
  { code: 'DK', label: 'Danimarca' },
  { code: 'FI', label: 'Finlandia' },
  { code: 'US', label: 'Stati Uniti' },
  { code: 'CA', label: 'Canada' },
  { code: 'BR', label: 'Brasile' },
  { code: 'AR', label: 'Argentina' },
  { code: 'MX', label: 'Messico' },
  { code: 'AU', label: 'Australia' },
  { code: 'NZ', label: 'Nuova Zelanda' },
  { code: 'JP', label: 'Giappone' },
  { code: 'CN', label: 'Cina' },
  { code: 'KR', label: 'Corea del Sud' },
  { code: 'IN', label: 'India' },
  { code: 'AE', label: 'Emirati Arabi' },
  { code: 'TR', label: 'Turchia' },
  { code: 'MA', label: 'Marocco' },
  { code: 'TN', label: 'Tunisia' },
  { code: 'EG', label: 'Egitto' },
  { code: 'ZA', label: 'Sudafrica' },
  { code: 'RU', label: 'Russia' },
  { code: 'UA', label: 'Ucraina' },
  { code: 'AL', label: 'Albania' },
  { code: 'RS', label: 'Serbia' },
  { code: 'BA', label: 'Bosnia ed Erzegovina' },
  { code: 'MK', label: 'Macedonia del Nord' },
  { code: 'MT', label: 'Malta' },
  { code: 'CY', label: 'Cipro' },
  { code: 'IS', label: 'Islanda' },
  { code: 'SG', label: 'Singapore' },
  { code: 'TH', label: 'Thailandia' },
  { code: 'VN', label: 'Vietnam' },
  { code: 'PH', label: 'Filippine' },
  { code: 'ID', label: 'Indonesia' },
  { code: 'MY', label: 'Malesia' },
  { code: 'IL', label: 'Israele' },
  { code: 'SA', label: 'Arabia Saudita' },
  { code: 'QA', label: 'Qatar' },
  { code: 'CL', label: 'Cile' },
  { code: 'CO', label: 'Colombia' },
  { code: 'PE', label: 'Perù' },
  { code: 'UY', label: 'Uruguay' },
  { code: 'VE', label: 'Venezuela' },
  { code: 'NG', label: 'Nigeria' },
  { code: 'KE', label: 'Kenya' },
  { code: 'GH', label: 'Ghana' },
];

export function countryLabel(code: string): string {
  return COUNTRY_OPTIONS.find((c) => c.code === code.toUpperCase())?.label ?? code;
}
