/** Brand e domini competitor / piattaforme travel-social rivali. */
export const COMPETITOR_TERMS: string[] = [
  'zonzers',
  'zonzer',
  'zonzers.com',
  'zonzers.it',
  'couchsurfing',
  'couch surfing',
  'couchsurfer',
  'couchsurfing.com',
  'nomadlist',
  'nomad list',
  'nomad-list',
  'nomadlist.com',
  'workaway',
  'workaway.info',
  'worldpackers',
  'worldpackers.com',
  'joinmytrip',
  'join my trip',
  'joinmytrip.com',
  'tourlina',
  'tourlina.com',
  'tripoto',
  'tripoto.com',
  'polarsteps',
  'polarsteps.com',
  'wanderlog',
  'wanderlog.com',
  'travelbuddy',
  'travel buddy',
  'travelbuddies',
  'travel buddies',
  'withlocals',
  'with locals',
];
