/**
 * Parole/frasi offensive aggiuntive (oltre al dataset inglese di obscenity).
 * Solo script latini qui — i non-latini stanno in NON_LATIN_TERMS.
 */

/** Singole parole / compound senza spazi (match con word-boundary). */
export const LATIN_PROFANITY: string[] = [
  // Italiano
  'cazzo',
  'cazzi',
  'cazzate',
  'cazzata',
  'coglione',
  'coglioni',
  'stronzo',
  'stronza',
  'stronzi',
  'puttana',
  'puttane',
  'troia',
  'troie',
  'vaffanculo',
  'vafanculo',
  'affanculo',
  'fanculo',
  'merda',
  'merde',
  'porcodio',
  'porcamadonna',
  'frocio',
  'froci',
  'ricchione',
  'ricchioni',
  'zoccola',
  'mignotta',
  'mignotte',
  'bagascia',
  'cornuto',
  'cornuta',
  'testadicazzo',
  'minchia',
  'minchie',
  'figa',
  'pompino',
  'pompini',
  'inculare',
  'inculato',
  'stupro',
  'stuprare',
  'stuprata',
  // Spagnolo
  'puta',
  'puto',
  'putas',
  'mierda',
  'joder',
  'jodido',
  'cabron',
  'cabrones',
  'gilipollas',
  'hijueputa',
  'hijoputa',
  'maricon',
  'maricones',
  'pendejo',
  'pendeja',
  'pendejos',
  'verga',
  'chinga',
  'chingar',
  'chingada',
  'pinche',
  'carajo',
  'culero',
  // Francese
  'putain',
  'merde',
  'connard',
  'connasse',
  'salope',
  'salopes',
  'encule',
  'enculer',
  'nique',
  'niquer',
  'fdp',
  'trouduc',
  'couille',
  'couilles',
  // Tedesco
  'scheisse',
  'fotze',
  'hurensohn',
  'arschloch',
  'wichser',
  'schlampe',
  'schlampen',
  'schwuchtel',
  'fotzen',
  'drecksau',
  // Portoghese
  'porra',
  'caralho',
  'foda',
  'foder',
  'fodase',
  'cuzao',
  'viado',
  'viados',
  'buceta',
  'bucetas',
  'putinha',
  'arrombado',
  // Olandese
  'kanker',
  'tyfus',
  'klootzak',
  // Polacco
  'kurwa',
  'chuj',
  'pierdol',
  'pierdolic',
  'jebac',
  'jebany',
  'dziwka',
  // Rumeno
  'pizda',
  'muie',
  'cacat',
  // Turco (latin)
  'siktir',
  'orospu',
  // Arabo / slang latinizzato
  'sharmuta',
  'sharmoota',
  'kusumak',
  'kussomak',
  'ibnkalb',
  'manyak',
];

/** Frasi multi-parola (match su testo normalizzato). */
export const LATIN_PHRASES: string[] = [
  // IT
  'figlio di puttana',
  'figlia di puttana',
  'porco dio',
  'porca madonna',
  'dio cane',
  'dio merda',
  'vai a cagare',
  'testa di cazzo',
  'faccia di merda',
  'pezzo di merda',
  'negro di merda',
  'frocio di merda',
  'troia di merda',
  'coglione di merda',
  // EN
  'kill yourself',
  'child porn',
  'child pornography',
  'rape her',
  'rape him',
  'rape you',
  'go kill yourself',
  'neck yourself',
  // ES
  'hijo de puta',
  'hija de puta',
  'la concha de tu madre',
  'me cago en',
  // FR
  'fils de pute',
  'fille de pute',
  'va te faire foutre',
  'nique ta mere',
  // DE
  'fick dich',
  'geh sterben',
  // PT
  'filho da puta',
  'filha da puta',
  'vai se foder',
  'toma no cu',
  // PL
  'jebac cie',
];

/** Termini in alfabeti non latini (substring match). */
export const NON_LATIN_TERMS: string[] = [
  // Russo / ucraino
  'хуй',
  'хуя',
  'пизда',
  'пізда',
  'блядь',
  'блять',
  'сука',
  'ебать',
  'ебал',
  'мудак',
  'пидор',
  'пидар',
  'гандон',
  'залупа',
  // Greco
  'μαλάκα',
  'μαλακα',
  'πούστη',
  'πουστη',
  'γαμώ',
  'γαμω',
  // Arabo
  'كس أمك',
  'كس امك',
  'شرموطة',
  'منيوك',
  'ابن الكلب',
  // Ebraico
  'זונה',
  'כוסעמק',
  'בן זונה',
  // Hindi
  'चूतिया',
  'भोसड़ी',
  'मादरचोद',
  'बहनचोद',
  // Cinese
  '傻逼',
  '操你',
  '草泥马',
  // Giapponese
  'バカ野郎',
  'きちがい',
];
